import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// components
import Footer from "./components/layouts/Footer";
import Header from "./components/layouts/Header";

export const metadata = {
  title: "Storefront",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={inter.className} lang="en">
      <body className="grid h-screen grid-rows-[auto_1fr_auto]">
        <Header />
        <main className="bg-blue-200">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
